Utilityの修正 - #9
ono-hikaru81/SuperiorButlers pull request #10
Opened 2021-11-05 07:21 UTC by Takuto-Miyoshi

Utilityを修正する

2021-11-08 06:01 UTC, ono-hikaru81 requested changes

2021-11-24 18:42 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Utility/Property.h
>          }
c023254 で演算子をごっそり実装したので、演算子関連のエラーは恐らく発生しないと思います。

2021-11-24 18:52 UTC, Takuto-Miyoshi commented
大体実装したので、ぼちぼち見て行ってください。
プルリクの説明欄的な場所に大体の変更点は書いてます。

変更ファイルの数が多いのは既存のコードに使われているUtility達を新しいものにしたためです。
コードの中身は(たぶん)弄ってません。

**Vector2**とか**ReadonlyProperty**は使われてなかったんで未確認です。
どちらも別環境から持ってきており、そっちでは動作確認済み。

###### いつの間にかドラフトじゃなくなってたんで手動でご連絡。

2021-11-26 05:14 UTC, ono-hikaru81 approved these changes

2021-11-26 06:38 UTC, merged