ステージ管理クラスの実装 #4
ono-hikaru81/SuperiorButlers pull request #13
Opened 2021-11-16 02:05 UTC by yuki-nakano

・外部からマップチップ情報の取得
・マップチップ情報の保存

2021-11-16 11:16 UTC, ono-hikaru81 approved these changes
問題ないと思います。

2021-11-17 07:56 UTC, ono-hikaru81 requested changes

2021-11-17 07:56 UTC, ono-hikaru81 commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +                p = strtok( nullptr, "," );
変数名 `P` だと何を意味しているのか伝わらないので具体的な名前にしましょう。

2021-11-17 07:58 UTC, ono-hikaru81 requested changes

2021-11-17 07:58 UTC, ono-hikaru81 commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +        while ( std::getline( file, str ) ) {
変数名 `str` だと何を意味しているのか伝わらないので具体的な名前にしましょう。

2021-11-17 08:30 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +                p = strtok( nullptr, "," );
a8a1a26 変数名を`chipNum`に変更しました。

2021-11-17 08:32 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +        while ( std::getline( file, str ) ) {
a8a1a26 変数名を`fileRow`に変更しました。

2021-11-19 02:15 UTC, Takuto-Miyoshi requested changes
一回書いたものは省略してる箇所があるので、よく見てね。

2021-11-19 02:15 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +#pragma warning( disable : 4996 )
エラーを消して良いわけがありません。

2021-11-19 02:15 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +        std::array<uint16_t, MAPCHIP_NUM> mapChip;
型名がなが～いので`auto`を使いたいところですが、初期化するのが面倒そうです。
`using 名前 = なが～い型名`とすると、型に別名をつけることができます。

2021-11-19 02:15 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +        int count { 0 };
サイズ指定できる整数型にしましょう。

2021-11-19 02:15 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +            char* p;
文字列を扱っているので`std::string`にするべきです。
が、`getline`関数は区切り文字の型に`char`を求めてるのでポインタじゃない普通の`char`でどうでしょうか。

2021-11-19 02:15 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +            p = std::strtok( (char*)str.c_str(), "," );
`std::strtok`ではなく`std::getline`の第三引数を利用しましょう。

C言語のキャストではなく`static_cast<>`を使うようにしましょう。

区切り文字は定数にしてみては。

2021-11-19 02:41 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.h
> +    constexpr uint8_t MAPCHIP_WHITE = 10;
106fa41b 定数名を修正しました

2021-11-21 16:18 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        bool InputStageFile( const char* file_name_ );
f2d39c85 引数を修正しました。

2021-11-21 16:20 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +        std::array<uint16_t, MAPCHIP_NUM> mapChip;
6ab27503 `using stageData = std::array<uint16_t, MAPCHIP_NUM>;`で型を簡潔にしました。`

2021-11-21 16:20 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +        int count { 0 };
ff77de95 型を`uint_16t`に訂正しました。

2021-11-21 16:23 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        std::array<uint16_t, MAPCHIP_NUM> GetStageDate( uint8_t stage_num_ ) { return stages[stage_num_]; };
6ab27503 誤字の訂正、戻り値と引数の修正をしました。

2021-11-25 07:48 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +#pragma warning( disable : 4996 )
9bf9de1d 削除しました。

2021-11-25 07:53 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +            p = std::strtok( (char*)str.c_str(), "," );
9bf9de1d 関数を修正しました。区切り文字はヘッダーに`constexpr char SPLIT = ',';`で宣言しました。

2021-11-25 07:54 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +            char* p;
9bf9de1d 関数を変更したので`char* p;`は削除しました。

2021-11-26 01:05 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        bool InputStageFile( const char* file_name_ );
引数は**const**と**左辺値参照**でとるようにしましょう。

2021-11-26 01:08 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        std::array<uint16_t, MAPCHIP_NUM> GetStageDate( uint8_t stage_num_ ) { return stages[stage_num_]; };
見逃してましたが、行末の **;** は不要かと思います。

2021-11-26 03:17 UTC, Takuto-Miyoshi requested changes

2021-11-26 03:17 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        std::vector<stageData> stages;
適当に`()`とかつけて初期化しておきましょう。

2021-12-01 01:27 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        std::vector<stageData> stages;
02bc7d2a 初期化しました。

2021-12-01 01:27 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.cpp
> +                mapChip[count] = std::atoi( chipNum.c_str() );
02bc7d2a 関数の変更をしました。

2021-12-01 01:27 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        std::array<uint16_t, MAPCHIP_NUM> GetStageDate( uint8_t stage_num_ ) { return stages[stage_num_]; };
02bc7d2a `;`を削除しました。

2021-12-01 01:27 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/StageManager.h
> +        bool InputStageFile( const char* file_name_ );
02bc7d2a 引数をコンスト参照に修正しました。

2021-12-01 01:50 UTC, Takuto-Miyoshi approved these changes

2021-12-02 04:29 UTC, merged