アニメーショ管理クラスの追加
ono-hikaru81/SuperiorButlers pull request #35
Opened 2021-12-17 00:56 UTC by yuki-nakano

- [ ] アニメーションの再生
- [ ] アニメーショの管理

2021-12-17 01:38 UTC, ono-hikaru81 approved these changes

2021-12-17 06:45 UTC, Takuto-Miyoshi requested changes
お願いしま。

2021-12-17 06:45 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +        AnimationList.at( name_ ).frameCount++;
**auto&** にすればコピーのコストがなくなり、`frameCount`の加算も`animationData.frameCount++`と書けます。

2021-12-17 06:45 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.h
> +        int32_t GetAnimationTexture( const std::string& name_, uint8_t texture_num_ );
`texture_num_`の型を**const参照**にすべきです。

2021-12-17 06:45 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +            for ( auto texture : data.second.textureList ) {
参照型にしないとコピーになってしまいます。

要素には変更を加えていないのでコンテナを`std::as_const`で**const**化しておくと良いです。
最良の範囲for文は`for( auto&& element : std::as_const(container) ){ }`らしいです。

2021-12-17 06:59 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +            fileName << file_name_ << std::setfill( '0' ) << std::setw( 3 ) << std::right << std::to_string( i + 1 ) << file_type_;
ここどうなってるのかよくわからないです。

埋め文字を`'0'`、文字列サイズを`3`、右寄せに設定した`fileName`に`file_name`+`index + 1` + 拡張子をということ？
埋め文字等々を設定したら読み込むファイル名が変わると思うのですが。

2021-12-18 08:54 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +        data.switchTime = switch_time_;
f8055275 `AnimationManager::Data data { .switchTime = switch_time_, .textureNum = texture_num_ };`に修正しました。

2021-12-18 08:55 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +        AnimationList.at( name_ ).frameCount++;
f8055275 修正しました。

2021-12-18 08:56 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.h
> +        int32_t GetAnimationTexture( const std::string& name_, uint8_t texture_num_ );
f8055275 訂正しました。

2021-12-18 08:56 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +            for ( auto texture : data.second.textureList ) {
f8055275 訂正しました。

2021-12-18 09:01 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +            fileName << file_name_ << std::setfill( '0' ) << std::setw( 3 ) << std::right << std::to_string( i + 1 ) << file_type_;
数字と拡張子を抜いたファイルパス+右寄せで０埋めされた三桁+拡張子にしてます。
title_BG_001.jpg～title_BG_020.jpgは読み込めました。

2021-12-21 08:29 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +            fileName << file_name_ << std::setfill( '0' ) << std::setw( 3 ) << std::right << std::to_string( i + 1 ) << file_type_;
理解です。

2021-12-21 08:44 UTC, Takuto-Miyoshi submitted a review, later dismissed
OKだと思います。

適当にコメントしてるので、気になったらよしなに修正しておいてください。

2021-12-21 08:44 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +            if ( handle == -1 ) { return false; }
`texture_num_`の値をミスった時すこしまずいかもしれない。
if文内に入った時点で読み込まれてたデータは、メモリ上に漂うのでは？と思う。

2021-12-21 08:44 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +        uint8_t textureNum { animationData.frameCount / animationData.switchTime % animationData.textureNum };
値が範囲外になりそうで怖い。
ならないなら問題ないですが。

2021-12-21 08:44 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.h
> +    static constexpr char JPEG[6] { ".jpg" };
要素数は5でいいのでは？
そもそも初期化してるので明示しなくても良いですが。

2021-12-23 04:21 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +            if ( handle == -1 ) { return false; }
7b11006a 読み込み失敗時にテクスチャハンドルを削除するように修正しました。

2021-12-23 04:21 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.h
> +    static constexpr char JPEG[6] { ".jpg" };
a3dfbd61 修正しました。

2021-12-23 07:37 UTC, Takuto-Miyoshi requested changes

2021-12-23 07:37 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +                }
`ReleaseAnimation`でも同じことしてるんで、**Data**構造体に『`textureList`の要素全てに`DeleteGraph`を適用する』関数を作ってみては。

2021-12-23 08:16 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/AnimationManager.cpp
> +                }
0a2d645e 構造体内にテクスチャ解放関数を追加しました。

2021-12-23 08:18 UTC, Takuto-Miyoshi submitted a review, later dismissed

2021-12-23 08:44 UTC, ono-hikaru81 approved these changes

2021-12-23 08:45 UTC, merged