SoundManager追加
ono-hikaru81/SuperiorButlers pull request #36
Opened 2021-12-17 08:07 UTC by hiroaki-saitou-0410

2021-12-17 09:43 UTC, Takuto-Miyoshi requested changes
お願いします。

2021-12-17 09:43 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +
全体をnamespaceでくくると
```
namespace spesium{
    void SoundManager::XXXX(){}

    void SoundManager::YYYY(){}
}
```
と一行を短く、逐一namespaceを書かなくて済みます。

クイックアクション💡を使う時は先に
```
namespace spesium{
}
``` 
と書いておくと、namespace内に入力してくれます。

2021-12-17 09:43 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +    playingBGM = BGMList.find(name)->second;
`find`はコストがかかるので最初に一回取得して、以降はそれを使うようにしましょう。
ほかの部分も同じように。

2021-12-17 09:43 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +}
この2つの関数って書き方が違うだけで、やってる事は`PlayBGM`と同じでは？

2021-12-17 09:43 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.h
> +#include <optional>
`Definition.h`と`optional`は使用していないので不要です。
`DxLib.h`はソース側でしか使用していないのでソース側でincludeするようにしましょう。

下手にヘッダでincludeしまくると、リンカエラーになったりコンパイルが長くなる原因になります。

2021-12-21 01:19 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.h
> +#include <optional>
79192a4 `Definition.h`を外すとstd::stringがエラーを出すので`string`をIncludeしました

2021-12-21 01:19 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +    playingBGM = BGMList.find(name)->second;
ef8825e 自分なりに変更しました

2021-12-21 01:19 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +
24bc756 namespaceでくくりました

2021-12-21 01:19 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.h
> +		virtual ~SoundManager() {}
84fe757 defaultに変更

2021-12-21 01:20 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.h
> +		int playingBGM;
f0810dc int32_tに変更

2021-12-21 08:47 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +
各関数の`spesium::`を消さないと、括った意味がないですよ。

2021-12-21 08:49 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +    playingBGM = BGMList.find(name)->second;
[変数の命名規則](https://github.com/ono-hikaru81/SuperiorButlers/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E5%91%BD%E5%90%8D%E8%A6%8F%E5%89%87)に反してること以外は良いと思います。

2021-12-22 01:59 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +}
1e8c315 ChangeBGMとPlayBGMの条件文は同じなのでまとめました。
ChangeBGMは関数のコードを変更して使うことも考えて残してますが、完全に要らない子のなるのなら削除します。

2021-12-22 01:59 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +    playingBGM = BGMList.find(name)->second;
00fb4bd 規則に準じて訂正しました。
まだ抜けがあったらお願いします。

2021-12-22 01:59 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +
62dc3ec 消しました

2021-12-22 04:51 UTC, Takuto-Miyoshi requested changes
是正漏れです。

2021-12-22 04:51 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +        if (!CheckSoundMem(handle))
`CheckSoundMem`の戻り値は**int**型なので、**bool**型のように使うのは良くないです。

2021-12-22 04:51 UTC, Takuto-Miyoshi commented on SpesiumBrothers/Src/Manager/SoundManager.h
> +		int32_t playingBGM;
メンバ変数は初期化しましょう。

2021-12-22 14:39 UTC, yuki-nakano commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +}
`ChangeBGM`は現在再生されているBGMの停止とあたらしいBGMの再生で、`RePlayBGM`は`StopBGM`で停止した時点からの途中再生をしてほしいです。

2021-12-23 04:36 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.h
> +		int32_t playingBGM;
22bb9c5 直した

2021-12-23 04:37 UTC, hiroaki-saitou-0410 commented on SpesiumBrothers/Src/Manager/SoundManager.cpp
> +        if (!CheckSoundMem(handle))
19c2ab3 戻り値のint型に合わせました

2021-12-23 06:29 UTC, Takuto-Miyoshi approved these changes
いいと思いますー。

2021-12-23 09:12 UTC, merged